<?php

namespace BookBundle\Repository;

/**
 * memberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class memberRepository extends \Doctrine\ORM\EntityRepository
{
}
